M48
; DRILL file KiCad 10.0.5 date 2026-09-10T20:41:07
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-10T20:41:07-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.700
%
G90
G05
T1
X14.94Y-14.94
T2
X30.1Y-36.69
X35.9Y-36.69
T3
X3.0Y-3.0
X3.0Y-39.0
X49.0Y-3.0
X55.0Y-39.0
M30
