M48
; DRILL file KiCad 10.0.5 date 2026-09-10T18:25:08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-10T18:25:08-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X8.1Y-36.69
X13.9Y-36.69
T2
X3.0Y-3.0
X3.0Y-39.0
X55.0Y-3.0
X55.0Y-39.0
M30
