from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

pnb1_skidl = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'ESP32-S3-MINI-1-N8', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ESP32-S3-MINI-1-N8'}), 'ref_prefix':'U', 'fplist':['artera:BULETM-SMD_ESP32-S3-MINI-1-N8'], 'footprint':'artera:BULETM-SMD_ESP32-S3-MINI-1-N8', 'keywords':'WiFi Modules', 'description':'', 'datasheet':'https://www.lcsc.com/datasheet/C2913206.pdf', 'pins':[
            Pin(num='1',name='GND',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='3V3',func=pin_types.PWRIN),
            Pin(num='4',name='IO0',func=pin_types.BIDIR),
            Pin(num='5',name='IO1',func=pin_types.BIDIR),
            Pin(num='6',name='IO2',func=pin_types.BIDIR),
            Pin(num='7',name='IO3',func=pin_types.BIDIR),
            Pin(num='8',name='IO4',func=pin_types.BIDIR),
            Pin(num='9',name='IO5',func=pin_types.BIDIR),
            Pin(num='10',name='IO6',func=pin_types.BIDIR),
            Pin(num='11',name='IO7',func=pin_types.BIDIR),
            Pin(num='12',name='IO8',func=pin_types.BIDIR),
            Pin(num='13',name='IO9',func=pin_types.BIDIR),
            Pin(num='14',name='IO10',func=pin_types.BIDIR),
            Pin(num='15',name='IO11',func=pin_types.BIDIR),
            Pin(num='16',name='IO12',func=pin_types.BIDIR),
            Pin(num='17',name='IO13',func=pin_types.BIDIR),
            Pin(num='18',name='IO14',func=pin_types.BIDIR),
            Pin(num='19',name='IO15',func=pin_types.BIDIR),
            Pin(num='20',name='IO16',func=pin_types.BIDIR),
            Pin(num='21',name='IO17',func=pin_types.BIDIR),
            Pin(num='22',name='IO18',func=pin_types.BIDIR),
            Pin(num='23',name='IO19',func=pin_types.BIDIR),
            Pin(num='24',name='IO20',func=pin_types.BIDIR),
            Pin(num='25',name='IO21',func=pin_types.BIDIR),
            Pin(num='26',name='IO26',func=pin_types.BIDIR),
            Pin(num='27',name='IO47',func=pin_types.BIDIR),
            Pin(num='28',name='IO33',func=pin_types.BIDIR),
            Pin(num='29',name='IO34',func=pin_types.BIDIR),
            Pin(num='30',name='IO48',func=pin_types.BIDIR),
            Pin(num='31',name='IO35',func=pin_types.BIDIR),
            Pin(num='32',name='IO36',func=pin_types.BIDIR),
            Pin(num='33',name='IO37',func=pin_types.BIDIR),
            Pin(num='34',name='IO38',func=pin_types.BIDIR),
            Pin(num='35',name='IO39',func=pin_types.BIDIR),
            Pin(num='36',name='IO40',func=pin_types.BIDIR),
            Pin(num='37',name='IO41',func=pin_types.BIDIR),
            Pin(num='38',name='IO42',func=pin_types.BIDIR),
            Pin(num='39',name='TXD0',func=pin_types.OUTPUT),
            Pin(num='40',name='RXD0',func=pin_types.INPUT),
            Pin(num='41',name='IO45',func=pin_types.BIDIR),
            Pin(num='42',name='GND',func=pin_types.PWRIN),
            Pin(num='43',name='GND',func=pin_types.PWRIN),
            Pin(num='44',name='IO46',func=pin_types.BIDIR),
            Pin(num='45',name='EN',func=pin_types.INPUT),
            Pin(num='46',name='GND',func=pin_types.PWRIN),
            Pin(num='47',name='GND',func=pin_types.PWRIN),
            Pin(num='48',name='GND',func=pin_types.PWRIN),
            Pin(num='49',name='GND',func=pin_types.PWRIN),
            Pin(num='50',name='GND',func=pin_types.PWRIN),
            Pin(num='51',name='GND',func=pin_types.PWRIN),
            Pin(num='52',name='GND',func=pin_types.PWRIN),
            Pin(num='53',name='GND',func=pin_types.PWRIN),
            Pin(num='54',name='GND',func=pin_types.PWRIN),
            Pin(num='55',name='GND',func=pin_types.PWRIN),
            Pin(num='56',name='GND',func=pin_types.PWRIN),
            Pin(num='57',name='GND',func=pin_types.PWRIN),
            Pin(num='58',name='GND',func=pin_types.PWRIN),
            Pin(num='59',name='GND',func=pin_types.PWRIN),
            Pin(num='60',name='GND',func=pin_types.PWRIN),
            Pin(num='GND',name='GND',func=pin_types.PWRIN)], 'unit_defs':[] }),
        Part(**{ 'name':'AMS1117-3.3', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AMS1117-3.3'}), 'ref_prefix':'U', 'fplist':['artera:SOT-223-3_L6.5-W3.4-P2.30-LS7.0-BR'], 'footprint':'artera:SOT-223-3_L6.5-W3.4-P2.30-LS7.0-BR', 'keywords':'Linear Voltage Regulators (LDO)', 'description':'', 'datasheet':'https://lcsc.com/product-detail/Low-Dropout-Regulators-LDO_AMS_AMS1117-3-3_AMS1117-3-3_C6186.html', 'pins':[
            Pin(num='1',name='GND',func=pin_types.PWRIN),
            Pin(num='2',name='VOUT',func=pin_types.PWROUT),
            Pin(num='3',name='VIN',func=pin_types.PWRIN),
            Pin(num='4',name='VOUT',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'SCD41-D-R2', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SCD41-D-R2'}), 'ref_prefix':'U', 'fplist':['artera:LGA-20_L10.1-W10.1-P1.25-TL_SCD41-D-R2'], 'footprint':'artera:LGA-20_L10.1-W10.1-P1.25-TL_SCD41-D-R2', 'keywords':'', 'description':'', 'datasheet':'https://www.lcsc.com/datasheet/C3659294.pdf', 'pins':[
            Pin(num='11',name='DNC',func=pin_types.PASSIVE),
            Pin(num='12',name='DNC',func=pin_types.PASSIVE),
            Pin(num='13',name='DNC',func=pin_types.PASSIVE),
            Pin(num='14',name='DNC',func=pin_types.PASSIVE),
            Pin(num='15',name='DNC',func=pin_types.PASSIVE),
            Pin(num='16',name='DNC',func=pin_types.PASSIVE),
            Pin(num='17',name='DNC',func=pin_types.PASSIVE),
            Pin(num='18',name='DNC',func=pin_types.PASSIVE),
            Pin(num='20',name='GND',func=pin_types.PWRIN),
            Pin(num='5',name='DNC',func=pin_types.PASSIVE),
            Pin(num='4',name='DNC',func=pin_types.PASSIVE),
            Pin(num='3',name='DNC',func=pin_types.PASSIVE),
            Pin(num='2',name='DNC',func=pin_types.PASSIVE),
            Pin(num='1',name='DNC',func=pin_types.PASSIVE),
            Pin(num='7',name='VDD',func=pin_types.PWRIN),
            Pin(num='19',name='VDDH',func=pin_types.PWRIN),
            Pin(num='9',name='SCL',func=pin_types.INPUT),
            Pin(num='10',name='SDA',func=pin_types.BIDIR),
            Pin(num='6',name='GND',func=pin_types.PWRIN),
            Pin(num='8',name='DNC',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'BH1750FVI-TR', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BH1750FVI-TR'}), 'ref_prefix':'U', 'fplist':['artera:WSOF-6_L2.6-W1.6-P0.50-TL-EP'], 'footprint':'artera:WSOF-6_L2.6-W1.6-P0.50-TL-EP', 'keywords':'Ambient Light Sensors', 'description':'', 'datasheet':'https://lcsc.com/product-detail/Sensors_ROHM_BH1750FVI-TR_BH1750FVI-TR_C78960.html', 'pins':[
            Pin(num='1',name='VCC',func=pin_types.PWRIN),
            Pin(num='2',name='ADDR',func=pin_types.INPUT),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='SDA',func=pin_types.BIDIR),
            Pin(num='5',name='DVI',func=pin_types.INPUT),
            Pin(num='6',name='SCL',func=pin_types.INPUT),
            Pin(num='7',name='EP',func=pin_types.PWRIN)], 'unit_defs':[] }),
        Part(**{ 'name':'USBLC6-2SC6_C2687116', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USBLC6-2SC6_C2687116'}), 'ref_prefix':'D', 'fplist':['artera:SOT-23-6_L2.9-W1.6-P0.95-LS2.8-BL'], 'footprint':'artera:SOT-23-6_L2.9-W1.6-P0.95-LS2.8-BL', 'keywords':'ESD Protection Devices', 'description':'', 'datasheet':'https://www.lcsc.com/datasheet/C2687116.pdf', 'pins':[
            Pin(num='1',name='I/O1',func=pin_types.PASSIVE),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='I/O2',func=pin_types.PASSIVE),
            Pin(num='4',name='I/O2',func=pin_types.PASSIVE),
            Pin(num='5',name='VBUS',func=pin_types.PWRIN),
            Pin(num='6',name='I/O1',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'TYPE-C-31-M-12', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TYPE-C-31-M-12'}), 'ref_prefix':'USBC', 'fplist':['artera:USB-C_SMD-TYPE-C-31-M-12_1'], 'footprint':'artera:USB-C_SMD-TYPE-C-31-M-12_1', 'keywords':'USB Connectors', 'description':'', 'datasheet':'https://lcsc.com/product-detail/USB-Type-C_Korean-Hroparts-Elec-TYPE-C-31-M-12_C165948.html', 'pins':[
            Pin(num='A1B12',name='GND',func=pin_types.PWROUT),
            Pin(num='A4B9',name='VBUS',func=pin_types.PWROUT),
            Pin(num='B8',name='SBU2',func=pin_types.PASSIVE),
            Pin(num='A5',name='CC1',func=pin_types.PASSIVE),
            Pin(num='B7',name='DN2',func=pin_types.BIDIR),
            Pin(num='A6',name='DP1',func=pin_types.BIDIR),
            Pin(num='A7',name='DN1',func=pin_types.BIDIR),
            Pin(num='B6',name='DP2',func=pin_types.BIDIR),
            Pin(num='A8',name='SBU1',func=pin_types.PASSIVE),
            Pin(num='B5',name='CC2',func=pin_types.PASSIVE),
            Pin(num='B4A9',name='VBUS',func=pin_types.PASSIVE),
            Pin(num='B1A12',name='GND',func=pin_types.PASSIVE),
            Pin(num='4',name='EH',func=pin_types.PASSIVE),
            Pin(num='3',name='EH',func=pin_types.PASSIVE),
            Pin(num='2',name='EH',func=pin_types.PASSIVE),
            Pin(num='1',name='EH',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'Header-Male-2.54_2x6', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Header-Male-2.54_2x6'}), 'ref_prefix':'P', 'fplist':['artera:HDR-TH_12P-P2.54-V-M-R2-C6-S2.54'], 'footprint':'artera:HDR-TH_12P-P2.54-V-M-R2-C6-S2.54', 'keywords':'Pin Headers', 'description':'', 'datasheet':'https://lcsc.com/product-detail/Male-Header_Double-Rows2-6-pitch2-54mm_C66689.html', 'pins':[
            Pin(num='1',name='1',func=pin_types.INPUT),
            Pin(num='2',name='2',func=pin_types.INPUT),
            Pin(num='3',name='3',func=pin_types.INPUT),
            Pin(num='4',name='4',func=pin_types.INPUT),
            Pin(num='5',name='5',func=pin_types.INPUT),
            Pin(num='6',name='6',func=pin_types.INPUT),
            Pin(num='7',name='7',func=pin_types.INPUT),
            Pin(num='8',name='8',func=pin_types.INPUT),
            Pin(num='9',name='9',func=pin_types.INPUT),
            Pin(num='10',name='10',func=pin_types.INPUT),
            Pin(num='11',name='11',func=pin_types.INPUT),
            Pin(num='12',name='12',func=pin_types.INPUT)], 'unit_defs':[] }),
        Part(**{ 'name':'Header-Male-2.54_1x4', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Header-Male-2.54_1x4'}), 'ref_prefix':'H', 'fplist':['artera:HDR-TH_4P-P2.54-V-M'], 'footprint':'artera:HDR-TH_4P-P2.54-V-M', 'keywords':'Pin Headers', 'description':'', 'datasheet':'https://lcsc.com/product-detail/Male-Header_Headers-Pins-1-4P-2-54mm-Straight-line_C124378.html', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE),
            Pin(num='3',name='3',func=pin_types.PASSIVE),
            Pin(num='4',name='4',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'TS-1088-AR02016', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TS-1088-AR02016'}), 'ref_prefix':'SW', 'fplist':['artera:SW-SMD_L3.9-W3.0-P4.45'], 'footprint':'artera:SW-SMD_L3.9-W3.0-P4.45', 'keywords':'Tactile Switches', 'description':'', 'datasheet':'https://lcsc.com/product-detail/Tactile-Switches_XUNPU-TS-1088-AR02016_C720477.html', 'pins':[
            Pin(num='2',name='2',func=pin_types.PASSIVE),
            Pin(num='1',name='1',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'0603WAF1002T5E', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'0603WAF1002T5E'}), 'ref_prefix':'R', 'fplist':['artera:R0603'], 'footprint':'artera:R0603', 'keywords':'Resistors', 'description':'', 'datasheet':'https://lcsc.com/product-detail/Chip-Resistor-Surface-Mount-UniOhm_10KR-1002-1_C25804.html', 'pins':[
            Pin(num='2',name='2',func=pin_types.PULLUP),
            Pin(num='1',name='1',func=pin_types.INPUT)], 'unit_defs':[] }),
        Part(**{ 'name':'0603WAF5101T5E', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'0603WAF5101T5E'}), 'ref_prefix':'R', 'fplist':['artera:R0603'], 'footprint':'artera:R0603', 'keywords':'Resistors', 'description':'', 'datasheet':'https://lcsc.com/product-detail/Chip-Resistor-Surface-Mount-UniOhm_5-1KR-5101-1_C23186.html', 'pins':[
            Pin(num='2',name='2',func=pin_types.INPUT),
            Pin(num='1',name='1',func=pin_types.PULLDN)], 'unit_defs':[] }),
        Part(**{ 'name':'0603WAF4701T5E', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'0603WAF4701T5E'}), 'ref_prefix':'R', 'fplist':['artera:R0603'], 'footprint':'artera:R0603', 'keywords':'Resistors', 'description':'', 'datasheet':'https://lcsc.com/product-detail/Chip-Resistor-Surface-Mount-UniOhm_4-7KR-4701-1_C23162.html', 'pins':[
            Pin(num='2',name='2',func=pin_types.PULLUP),
            Pin(num='1',name='1',func=pin_types.INPUT)], 'unit_defs':[] }),
        Part(**{ 'name':'0603WAF1001T5E', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'0603WAF1001T5E'}), 'ref_prefix':'R', 'fplist':['artera:R0603'], 'footprint':'artera:R0603', 'keywords':'Resistors', 'description':'', 'datasheet':'https://lcsc.com/product-detail/Chip-Resistor-Surface-Mount-UniOhm_1KR-1001-1_C21190.html', 'pins':[
            Pin(num='2',name='2',func=pin_types.PULLUP),
            Pin(num='1',name='1',func=pin_types.INPUT)], 'unit_defs':[] }),
        Part(**{ 'name':'0603WAF3300T5E', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'0603WAF3300T5E'}), 'ref_prefix':'R', 'fplist':['artera:R0603'], 'footprint':'artera:R0603', 'keywords':'Resistors', 'description':'', 'datasheet':'https://lcsc.com/product-detail/Chip-Resistor-Surface-Mount-UniOhm_330R-3300-1_C23138.html', 'pins':[
            Pin(num='2',name='2',func=pin_types.PULLUP),
            Pin(num='1',name='1',func=pin_types.INPUT)], 'unit_defs':[] }),
        Part(**{ 'name':'CC0603KRX7R9BB104', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'CC0603KRX7R9BB104'}), 'ref_prefix':'C', 'fplist':['artera:C0603'], 'footprint':'artera:C0603', 'keywords':'Capacitors', 'description':'', 'datasheet':'https://lcsc.com/product-detail/Multilayer-Ceramic-Capacitors-MLCC-SMD-SMT_100nF-104-10-50V_C14663.html', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'CL10A105KB8NNNC', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'CL10A105KB8NNNC'}), 'ref_prefix':'C', 'fplist':['artera:C0603'], 'footprint':'artera:C0603', 'keywords':'Capacitors', 'description':'', 'datasheet':'https://lcsc.com/product-detail/Multilayer-Ceramic-Capacitors-MLCC-SMD-SMT_SAMSUNG_CL10A105KB8NNNC_1uF-105-10-50V_C15849.html', 'pins':[
            Pin(num='2',name='2',func=pin_types.PASSIVE),
            Pin(num='1',name='1',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'CL21A106KAYNNNE', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'CL21A106KAYNNNE'}), 'ref_prefix':'C', 'fplist':['artera:C0805'], 'footprint':'artera:C0805', 'keywords':'Capacitors', 'description':'', 'datasheet':'https://lcsc.com/product-detail/Multilayer-Ceramic-Capacitors-MLCC-SMD-SMT_SAMSUNG_CL21A106KAYNNNE_10uF-106-10-25V_C15850.html', 'pins':[
            Pin(num='2',name='2',func=pin_types.PASSIVE),
            Pin(num='1',name='1',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'TAJA226K010RNJ', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TAJA226K010RNJ'}), 'ref_prefix':'C', 'fplist':['artera:CASE-A_3216'], 'footprint':'artera:CASE-A_3216', 'keywords':'Tantalum Capacitors', 'description':'', 'datasheet':'https://lcsc.com/product-detail/Tantalum-Capacitors_AVX_TAJA226K010RNJ_22uF-226-10-10V_C11366.html', 'pins':[
            Pin(num='1',name='1',func=pin_types.INPUT),
            Pin(num='2',name='2',func=pin_types.INPUT)], 'unit_defs':[] }),
        Part(**{ 'name':'KT-0603R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'KT-0603R'}), 'ref_prefix':'LED', 'fplist':['artera:LED-SMD_L1.6-W0.8-R-RD'], 'footprint':'artera:LED-SMD_L1.6-W0.8-R-RD', 'keywords':'Light Emitting Diodes (LED)', 'description':'', 'datasheet':'https://lcsc.com/product-detail/Light-Emitting-Diodes-LED_Red-LED-0603_C2286.html', 'pins':[
            Pin(num='2',name='K',func=pin_types.PASSIVE),
            Pin(num='1',name='A',func=pin_types.PASSIVE)], 'unit_defs':[] })])